--BELUM DIBUAT FUNCTION

SELECT
    now() AS insertdate,
    idcabang,
    namacabang,
    nopolisi,
    -- MTD bulan berjalan
    COUNT(DISTINCT CASE WHEN bulan_ke = 0 THEN transaksi_key END) AS mtd_h_1,
    SUM(CASE WHEN bulan_ke = 0 THEN qty END) AS mtd_h_1_qty,
    SUM(CASE WHEN bulan_ke = 0 THEN subtotal END) AS mtd_h_1_value,
    -- M-1 s/d M-36
    COUNT(DISTINCT CASE WHEN bulan_ke = 1 THEN transaksi_key END) AS m_1,
    SUM(CASE WHEN bulan_ke = 1 THEN qty END) AS m_1_qty,
    SUM(CASE WHEN bulan_ke = 1 THEN subtotal END) AS m_1_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 2 THEN transaksi_key END) AS m_2,
    SUM(CASE WHEN bulan_ke = 2 THEN qty END) AS m_2_qty,
    SUM(CASE WHEN bulan_ke = 2 THEN subtotal END) AS m_2_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 3 THEN transaksi_key END) AS m_3,
    SUM(CASE WHEN bulan_ke = 3 THEN qty END) AS m_3_qty,
    SUM(CASE WHEN bulan_ke = 3 THEN subtotal END) AS m_3_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 4 THEN transaksi_key END) AS m_4,
    SUM(CASE WHEN bulan_ke = 4 THEN qty END) AS m_4_qty,
    SUM(CASE WHEN bulan_ke = 4 THEN subtotal END) AS m_4_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 5 THEN transaksi_key END) AS m_5,
    SUM(CASE WHEN bulan_ke = 5 THEN qty END) AS m_5_qty,
    SUM(CASE WHEN bulan_ke = 5 THEN subtotal END) AS m_5_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 6 THEN transaksi_key END) AS m_6,
    SUM(CASE WHEN bulan_ke = 6 THEN qty END) AS m_6_qty,
    SUM(CASE WHEN bulan_ke = 6 THEN subtotal END) AS m_6_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 7 THEN transaksi_key END) AS m_7,
    SUM(CASE WHEN bulan_ke = 7 THEN qty END) AS m_7_qty,
    SUM(CASE WHEN bulan_ke = 7 THEN subtotal END) AS m_7_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 8 THEN transaksi_key END) AS m_8,
    SUM(CASE WHEN bulan_ke = 8 THEN qty END) AS m_8_qty,
    SUM(CASE WHEN bulan_ke = 8 THEN subtotal END) AS m_8_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 9 THEN transaksi_key END) AS m_9,
    SUM(CASE WHEN bulan_ke = 9 THEN qty END) AS m_9_qty,
    SUM(CASE WHEN bulan_ke = 9 THEN subtotal END) AS m_9_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 10 THEN transaksi_key END) AS m_10,
    SUM(CASE WHEN bulan_ke = 10 THEN qty END) AS m_10_qty,
    SUM(CASE WHEN bulan_ke = 10 THEN subtotal END) AS m_10_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 11 THEN transaksi_key END) AS m_11,
    SUM(CASE WHEN bulan_ke = 11 THEN qty END) AS m_11_qty,
    SUM(CASE WHEN bulan_ke = 11 THEN subtotal END) AS m_11_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 12 THEN transaksi_key END) AS m_12,
    SUM(CASE WHEN bulan_ke = 12 THEN qty END) AS m_12_qty,
    SUM(CASE WHEN bulan_ke = 12 THEN subtotal END) AS m_12_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 13 THEN transaksi_key END) AS m_13,
    SUM(CASE WHEN bulan_ke = 13 THEN qty END) AS m_13_qty,
    SUM(CASE WHEN bulan_ke = 13 THEN subtotal END) AS m_13_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 14 THEN transaksi_key END) AS m_14,
    SUM(CASE WHEN bulan_ke = 14 THEN qty END) AS m_14_qty,
    SUM(CASE WHEN bulan_ke = 14 THEN subtotal END) AS m_14_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 15 THEN transaksi_key END) AS m_15,
    SUM(CASE WHEN bulan_ke = 15 THEN qty END) AS m_15_qty,
    SUM(CASE WHEN bulan_ke = 15 THEN subtotal END) AS m_15_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 16 THEN transaksi_key END) AS m_16,
    SUM(CASE WHEN bulan_ke = 16 THEN qty END) AS m_16_qty,
    SUM(CASE WHEN bulan_ke = 16 THEN subtotal END) AS m_16_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 17 THEN transaksi_key END) AS m_17,
    SUM(CASE WHEN bulan_ke = 17 THEN qty END) AS m_17_qty,
    SUM(CASE WHEN bulan_ke = 17 THEN subtotal END) AS m_17_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 18 THEN transaksi_key END) AS m_18,
    SUM(CASE WHEN bulan_ke = 18 THEN qty END) AS m_18_qty,
    SUM(CASE WHEN bulan_ke = 18 THEN subtotal END) AS m_18_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 19 THEN transaksi_key END) AS m_19,
    SUM(CASE WHEN bulan_ke = 19 THEN qty END) AS m_19_qty,
    SUM(CASE WHEN bulan_ke = 19 THEN subtotal END) AS m_19_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 20 THEN transaksi_key END) AS m_20,
    SUM(CASE WHEN bulan_ke = 20 THEN qty END) AS m_20_qty,
    SUM(CASE WHEN bulan_ke = 20 THEN subtotal END) AS m_20_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 21 THEN transaksi_key END) AS m_21,
    SUM(CASE WHEN bulan_ke = 21 THEN qty END) AS m_21_qty,
    SUM(CASE WHEN bulan_ke = 21 THEN subtotal END) AS m_21_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 22 THEN transaksi_key END) AS m_22,
    SUM(CASE WHEN bulan_ke = 22 THEN qty END) AS m_22_qty,
    SUM(CASE WHEN bulan_ke = 22 THEN subtotal END) AS m_22_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 23 THEN transaksi_key END) AS m_23,
    SUM(CASE WHEN bulan_ke = 23 THEN qty END) AS m_23_qty,
    SUM(CASE WHEN bulan_ke = 23 THEN subtotal END) AS m_23_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 24 THEN transaksi_key END) AS m_24,
    SUM(CASE WHEN bulan_ke = 24 THEN qty END) AS m_24_qty,
    SUM(CASE WHEN bulan_ke = 24 THEN subtotal END) AS m_24_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 25 THEN transaksi_key END) AS m_25,
    SUM(CASE WHEN bulan_ke = 25 THEN qty END) AS m_25_qty,
    SUM(CASE WHEN bulan_ke = 25 THEN subtotal END) AS m_25_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 26 THEN transaksi_key END) AS m_26,
    SUM(CASE WHEN bulan_ke = 26 THEN qty END) AS m_26_qty,
    SUM(CASE WHEN bulan_ke = 26 THEN subtotal END) AS m_26_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 27 THEN transaksi_key END) AS m_27,
    SUM(CASE WHEN bulan_ke = 27 THEN qty END) AS m_27_qty,
    SUM(CASE WHEN bulan_ke = 27 THEN subtotal END) AS m_27_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 28 THEN transaksi_key END) AS m_28,
    SUM(CASE WHEN bulan_ke = 28 THEN qty END) AS m_28_qty,
    SUM(CASE WHEN bulan_ke = 28 THEN subtotal END) AS m_28_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 29 THEN transaksi_key END) AS m_29,
    SUM(CASE WHEN bulan_ke = 29 THEN qty END) AS m_29_qty,
    SUM(CASE WHEN bulan_ke = 29 THEN subtotal END) AS m_29_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 30 THEN transaksi_key END) AS m_30,
    SUM(CASE WHEN bulan_ke = 30 THEN qty END) AS m_30_qty,
    SUM(CASE WHEN bulan_ke = 30 THEN subtotal END) AS m_30_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 31 THEN transaksi_key END) AS m_31,
    SUM(CASE WHEN bulan_ke = 31 THEN qty END) AS m_31_qty,
    SUM(CASE WHEN bulan_ke = 31 THEN subtotal END) AS m_31_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 32 THEN transaksi_key END) AS m_32,
    SUM(CASE WHEN bulan_ke = 32 THEN qty END) AS m_32_qty,
    SUM(CASE WHEN bulan_ke = 32 THEN subtotal END) AS m_32_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 33 THEN transaksi_key END) AS m_33,
    SUM(CASE WHEN bulan_ke = 33 THEN qty END) AS m_33_qty,
    SUM(CASE WHEN bulan_ke = 33 THEN subtotal END) AS m_33_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 34 THEN transaksi_key END) AS m_34,
    SUM(CASE WHEN bulan_ke = 34 THEN qty END) AS m_34_qty,
    SUM(CASE WHEN bulan_ke = 34 THEN subtotal END) AS m_34_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 35 THEN transaksi_key END) AS m_35,
    SUM(CASE WHEN bulan_ke = 35 THEN qty END) AS m_35_qty,
    SUM(CASE WHEN bulan_ke = 35 THEN subtotal END) AS m_35_value,
    COUNT(DISTINCT CASE WHEN bulan_ke = 36 THEN transaksi_key END) AS m_36,
    SUM(CASE WHEN bulan_ke = 36 THEN qty END) AS m_36_qty,
    SUM(CASE WHEN bulan_ke = 36 THEN subtotal END) AS m_36_value
FROM (
    SELECT 
        x.idcabang,
        x.namacabang,
        UPPER(x.nopolisi::text) AS nopolisi,
        CONCAT(x.kodetoko, x.nomortransaksi) AS transaksi_key,
        x.qty,
        x.subtotal,
        -- Hitung selisih bulan dari sekarang
--        (EXTRACT(YEAR FROM age((current_date - 1)::date, x.tanggal)) * 12 + 
--         EXTRACT(MONTH FROM age((current_date - 1)::date, x.tanggal)))::integer AS bulan_ke,
         (EXTRACT(YEAR FROM age((current_date - INTERVAL '1 day')::date, x.tanggal)) * 12 + 
         EXTRACT(MONTH FROM age((current_date - INTERVAL '1 day')::date, x.tanggal)))::integer AS bulan_ke
    FROM public.smi_rms22_transaksi_toko_perjenis_member_v3 x
    WHERE x.idcabang = 5
        AND x.idjenisproduk <> 4 
        AND x.statusproduk <> 'K'::bpchar
        AND x.category IN ('ACCU','BODY THROTTLE','ENGINE FLUSH','INJECTOR CLEANER',
                          'OIL','TIRE SEALANT','TUBELESS','TUBETYPE')
        AND x.kodeproduk != '3091844001'
        AND x.nopolisi IS NOT NULL 
        AND x.nopolisi <> '' 
        AND x.nopolisi in ('A3305WU','')
        -- Filter tanggal: hanya data 3 tahun terakhir
        AND x.tanggal >= ((current_date - 1) - INTERVAL '36 months')::date
) AS data_terfilter
GROUP BY idcabang, namacabang, nopolisi
HAVING COUNT(DISTINCT CASE WHEN bulan_ke = 0 THEN transaksi_key END) > 0;